FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Set npm config to avoid exit handler issue
RUN npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-timeout 300000 && \
    NODE_ENV=development npm install --legacy-peer-deps

COPY . .

RUN NODE_ENV=development npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
