apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finbot-ingress
  namespace: finbot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: nevilanghan.me
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: node-backend
            port:
              number: 2590
      - path: /python-api
        pathType: Prefix
        backend:
          service:
            name: python-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finbot-frontend
            port:
              number: 80
  - host: www.nevilanghan.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finbot-frontend
            port:
              number: 80
