apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-backend-hpa
  namespace: finbot
  labels:
    app: node-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-backend
  minReplicas: 1                         # normal: 1 pod running
  maxReplicas: 2                         # high CPU: max 2 pods (1 extra only)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60         # trigger when CPU > 60%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1                       # add only 1 pod at a time
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1                       # remove only 1 pod at a time
          periodSeconds: 120
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-backend-hpa
  namespace: finbot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-backend
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: finbot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finbot-frontend
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
