apiVersion: v1
kind: ConfigMap
metadata:
  name: python-backend-config
  namespace: finbot
data:
  AWS_REGION: "us-east-1"
  NODE_WEBHOOK_URL: "http://node-backend:2590"
  PINECONE_ENVIRONMENT: "us-east-1-aws"
  HF_HOME: "/app/models"
  TRANSFORMERS_CACHE: "/app/models"
  TRANSFORMERS_OFFLINE: "1"
  HF_DATASETS_OFFLINE: "1"
